

/Generator/SingleParticle/particle gamma
#/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 137 keV
/Generator/SingleParticle/max_energy 137 keV
/Generator/SingleParticle/region IN_FRONT_SCINTILLATOR
#/Generator/SingleParticle/region INSIDE_CIGAR
#/Generator/Kr83mGenerator/region INSIDE_CIGAR

/Geometry/Cigar/pressure 1 bar
/Geometry/Cigar/fiber_diameter 1 mm
/Geometry/Cigar/coating TPB
/Geometry/Cigar/fiber_type Y11
/Geometry/Cigar/gas Xe

/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            1
/nexus/persistency/start_id   0
/nexus/persistency/output_file Cigar.next
