/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/Geometry/Fib_SiPM_cyl/length 3. cm
#/Geometry/Fib_SiPM_cyl/radius .5 mm
/Geometry/Fib_SiPM_cyl/radius 1. mm
/Geometry/Fib_SiPM_cyl/radius_cyl 1. cm

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/region WHOLE_VOL
/Generator/SingleParticle/min_energy 7 eV
/Generator/SingleParticle/max_energy 7 eV
#/Generator/SingleParticle/min_costheta 0
#/Generator/SingleParticle/max_costheta 0
#/Generator/SingleParticle/min_phi 0
#/Generator/SingleParticle/max_phi 0

/process/optical/processActivation Cerenkov false

### PHYSICS
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

/nexus/persistency/outputFile Fib_SiPM_cyl.next
