
# Generator______________________________________________________
#/Generator/SingleParticle/particle opticalphoton
#/Generator/SingleParticle/min_energy 7 eV
#/Generator/SingleParticle/max_energy 7 eV
#/Generator/SingleParticle/region VOLUME

/Generator/Kr83mGenerator/region ACTIVE

# Xenon______________________________________________________
/Geometry/Fib_pan_meth/LXe false
/Geometry/Fib_pan_meth/pressure 10. bar

# barrel______________________________________________________
/Geometry/Fib_pan_meth/panel_length 150. cm
/Geometry/Fib_pan_meth/radius 50 cm
/Geometry/Fib_pan_meth/panel_width 17 cm

#/Geometry/Fib_pan_meth/panel_length 1.5 cm
#/Geometry/Fib_pan_meth/radius .5 cm
#/Geometry/Fib_pan_meth/panel_width .3 cm

#/Geometry/Fib_pan_meth/panel_length 5 cm
#/Geometry/Fib_pan_meth/radius 2 cm
#/Geometry/Fib_pan_meth/panel_width 1 cm

# teflon______________________________________________________
/Geometry/Fib_pan_meth/teflon_thickness 1. mm

/Geometry/Fib_pan_meth/caps_visibility true
/Geometry/Fib_pan_meth/teflon_visibility true

# sensor______________________________________________________
#/Geometry/Fib_pan_meth/sensor_type PERFECT
#/Geometry/Fib_pan_meth/sensor_type SiPM_FBK
/Geometry/Fib_pan_meth/sensor_type SiPM_Hamamatsu
#/Geometry/Fib_pan_meth/sensor_type PMT

/Geometry/Fib_pan_meth/sensor_visibility true

# fibers______________________________________________________
/Geometry/Fib_pan_meth/fiber_diameter 1 mm
/Geometry/Fib_pan_meth/coated true
/Geometry/Fib_pan_meth/fiber_type Y11

# methacrylate______________________________________________________
/Geometry/Fib_pan_meth/methacrylate false
#/Geometry/Fib_pan_meth/window_thickness 5. mm
/Geometry/Fib_pan_meth/window_thickness .5 mm


/PhysicsList/Nexus/photoelectric false
/process/optical/processActivation Cerenkov false

/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/output_file Fib_pan_meth.next
