/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

# fibers______________________________________________________
#/Geometry/Fib_box_struct/length 1. m
/Geometry/Fib_box_struct/length 25. cm

/Geometry/Fib_box_struct/diameter 1. mm

# sensor______________________________________________________
#/Geometry/Fib_box_struct/sensor_type PERFECT
#/Geometry/Fib_box_struct/sensor_type SiPM
/Geometry/Fib_box_struct/sensor_type PMT

/Geometry/Fib_box_struct/sensor_width 1.6 mm
/Geometry/Fib_box_struct/sensor_height 40. mm
#/Geometry/Fib_box_struct/sensor_height 70. mm

/Geometry/Fib_box_struct/sensor_visibility true



/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/region CENTER
#/Generator/SingleParticle/region VOLUME

#/Generator/SingleParticle/min_energy 7 eV # Y11 with TPB
#/Generator/SingleParticle/max_energy 7 eV # Y11 with TPB
/Generator/SingleParticle/min_energy 2.88 eV # Y11
/Generator/SingleParticle/max_energy 2.88 eV # Y11
#/Generator/SingleParticle/min_energy 3.35 eV # B2
#/Generator/SingleParticle/max_energy 3.35 eV # B2

/Generator/SingleParticle/min_costheta 0.98995 # costheta_min = box_z/sqrt((box_xy/2)² + box_z²)
/Generator/SingleParticle/max_costheta 1.
/Generator/SingleParticle/min_phi 0
/Generator/SingleParticle/max_phi 90.

/process/optical/processActivation Cerenkov false

### PHYSICS
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

/nexus/persistency/outputFile Fib_box_struct.next
