
# Generator______________________________________________________
#/Generator/SingleParticle/particle opticalphoton
#/Generator/SingleParticle/min_energy 7 eV
#/Generator/SingleParticle/max_energy 7 eV
#/Generator/SingleParticle/region VOLUME

/Generator/Kr83mGenerator/region VOLUME

# Xenon______________________________________________________
/Geometry/Fib_pan_meth_OLD/LXe false
/Geometry/Fib_pan_meth_OLD/pressure 10. bar

# barrel______________________________________________________
/Geometry/Fib_pan_meth_OLD/length 150. cm
/Geometry/Fib_pan_meth_OLD/radius 50 cm
/Geometry/Fib_pan_meth_OLD/panel_width 17 cm

#/Geometry/Fib_pan_meth_OLD/length 1.5 cm
#/Geometry/Fib_pan_meth_OLD/radius .5 cm
#/Geometry/Fib_pan_meth_OLD/panel_width .3 cm

#/Geometry/Fib_pan_meth_OLD/length 5 cm
#/Geometry/Fib_pan_meth_OLD/radius .5 cm
#/Geometry/Fib_pan_meth_OLD/panel_width 2 cm

# teflon______________________________________________________
/Geometry/Fib_pan_meth_OLD/teflon_thickness 1. mm

/Geometry/Fib_pan_meth_OLD/caps_visibility true
/Geometry/Fib_pan_meth_OLD/teflon_visibility true

# sensor______________________________________________________
#/Geometry/Fib_pan_meth_OLD/sensor_type PERFECT
#/Geometry/Fib_pan_meth_OLD/sensor_type SiPM_FBK
/Geometry/Fib_pan_meth_OLD/sensor_type SiPM_Hamamatsu
#/Geometry/Fib_pan_meth_OLD/sensor_type PMT

/Geometry/Fib_pan_meth_OLD/sensor_visibility true

# fibers______________________________________________________
/Geometry/Fib_pan_meth_OLD/fiber_diameter 1 mm
/Geometry/Fib_pan_meth_OLD/coated true
/Geometry/Fib_pan_meth_OLD/fiber_type Y11

# methacrylate______________________________________________________
/Geometry/Fib_pan_meth_OLD/methacrylate false
#/Geometry/Fib_pan_meth_OLD/window_thickness 5. mm
/Geometry/Fib_pan_meth_OLD/window_thickness .5 mm


/PhysicsList/Nexus/photoelectric false
/process/optical/processActivation Cerenkov false

/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0
/nexus/persistency/output_file Fib_pan_meth_OLD.next
