
# barrel______________________________________________________
/Geometry/Fiber_barrel_meth/length 200. cm
/Geometry/Fiber_barrel_meth/radius_cyl 50 cm # NEXT100 iner_diam ~= 100cm

#/Geometry/Fiber_barrel_meth/length 2. cm
#/Geometry/Fiber_barrel_meth/radius_cyl .5 cm

# teflon______________________________________________________
/Geometry/Fiber_barrel_meth/teflon_thickness 5. mm

/Geometry/Fiber_barrel_meth/caps_visibility true
/Geometry/Fiber_barrel_meth/teflon_visibility true

# sensor______________________________________________________
/Geometry/Fiber_barrel_meth/sensor_type PERFECT
#/Geometry/Fiber_barrel_meth/sensor_type SiPM_FBK
#/Geometry/Fiber_barrel_meth/sensor_type SiPM_Hamamatsu
#/Geometry/Fiber_barrel_meth/sensor_type PMT

/Geometry/Fiber_barrel_meth/sensor_visibility true

# methacrylate______________________________________________________
/Geometry/Fiber_barrel_meth/methacrylate false
#/Geometry/Fiber_barrel_meth/window_thickness 5. mm
/Geometry/Fiber_barrel_meth/window_thickness 1. mm

# vertex______________________________________________________
/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/region VOLUME

# fibers______________________________________________________
/Geometry/Fiber_barrel_meth/diameter 1. mm

/Geometry/Fiber_barrel_meth/coated true

#/Geometry/Fiber_barrel_meth/fiber_type Y11
/Geometry/Fiber_barrel_meth/fiber_type B2
/Generator/SingleParticle/max_energy 7 eV # Y11 with TPB or B2 with TPH (Xe scintillation)
/Generator/SingleParticle/min_energy 7 eV # Y11 with TPB or B2 with TPH (Xe scintillation)

#/Geometry/Fiber_barrel_meth/fiber_type Y11
#/Generator/SingleParticle/min_energy 2.88 eV # Y11 uncoated
#/Generator/SingleParticle/max_energy 2.88 eV # Y11 uncoated

#/Geometry/Fiber_barrel_meth/fiber_type B2
#/Generator/SingleParticle/min_energy 3.35 eV # B2 uncoated
#/Generator/SingleParticle/max_energy 3.35 eV # B2 uncoated


#/Generator/SingleParticle/min_costheta 0
#/Generator/SingleParticle/max_costheta 0
#/Generator/SingleParticle/min_phi 0
#/Generator/SingleParticle/max_phi 0

/process/optical/processActivation Cerenkov false

### PHYSICS
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

/run/verbose 1
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0

### JOB CONTROL
/nexus/random_seed            -1
/nexus/persistency/start_id   0

/nexus/persistency/output_file Fiber_barrel_meth.next
