/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/Geometry/Fiber_barrel_meth/length 3. cm
#/Geometry/Fiber_barrel_meth/radius .5 mm
/Geometry/Fiber_barrel_meth/radius 1. mm
/Geometry/Fiber_barrel_meth/radius_cyl 1. cm

# sensor______________________________________________________
#/Geometry/Fiber_barrel_meth/sensor_type PERFECT
/Geometry/Fiber_barrel_meth/sensor_type SiPM_FBK
#/Geometry/Fiber_barrel_meth/sensor_type SiPM_Hamamatsu
#/Geometry/Fiber_barrel_meth/sensor_type PMT

/Geometry/Fiber_barrel_meth/sensor_visibility true

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/region WHOLE_VOL

/Generator/SingleParticle/max_energy 7 eV # Y11 with TPB
/Generator/SingleParticle/min_energy 7 eV # Y11 with TPB

#/Geometry/Fiber_barrel_meth/fiber_type Y11
#/Generator/SingleParticle/min_energy 2.88 eV # Y11
#/Generator/SingleParticle/max_energy 2.88 eV # Y11

#/Geometry/Fiber_barrel_meth/fiber_type B2
#/Generator/SingleParticle/min_energy 3.35 eV # B2
#/Generator/SingleParticle/max_energy 3.35 eV # B2


#/Generator/SingleParticle/min_costheta 0
#/Generator/SingleParticle/max_costheta 0
#/Generator/SingleParticle/min_phi 0
#/Generator/SingleParticle/max_phi 0

/process/optical/processActivation Cerenkov false

### PHYSICS
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

/nexus/persistency/outputFile Fiber_barrel_meth.next
