/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

/Geometry/FibreTest/length 1. cm
/Geometry/FibreTest/radius 1. mm

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/region WHOLE_VOL
/Generator/SingleParticle/min_energy 2.88 eV
/Generator/SingleParticle/max_energy 2.88 eV
#/Generator/SingleParticle/min_costheta 0
#/Generator/SingleParticle/max_costheta 0
#/Generator/SingleParticle/min_phi 0
#/Generator/SingleParticle/max_phi 0

/process/optical/processActivation Cerenkov false

### PHYSICS
/PhysicsList/Nexus/clustering           true
/PhysicsList/Nexus/drift                true
/PhysicsList/Nexus/electroluminescence  true

/nexus/persistency/outputFile OpticalFibre.next