## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO_S1_table.config.mac
##
## Configuration macro to simulate primary scintillation light
## for look-up tables in the NEXT-10. detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

# VERBOSITY
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

# JOB CONTROL
/nexus/random_seed -2

# GEOMETRY
/Geometry/NextHDDEMO/pressure 10. bar

## fibers______________________________________________________
/Geometry/NextHDDEMO/fiber_type Y11 ### (Y11, B2)
/Geometry/NextHDDEMO/coated true

## sensor______________________________________________________
/Geometry/NextHDDEMO/sensor_type SiPM_Hamamatsu ### (PERFECT, SiPM_FBK, SiPM_Hamamatsu, PMT)

# Visibilities
#NextHDDEMO
#/Geometry/NextHDDEMO/ics_vis false
#/Geometry/NextHDDEMO/shielding_vis false
#/Geometry/NextHDDEMO/vessel_vis false
#NextHDDEMOOpticalGeometry
/Geometry/NextHDDEMO/field_cage_vis false
/Geometry/NextHDDEMO/sensor_visibility false
/Geometry/NextHDDEMO/panels_visibility false
/Geometry/NextHDDEMO/fibers_visibility false

# GENERATION
#/Geometry/NextHDDEMO/specific_vertex 0 3 10.  mm

/Generator/ScintGenerator/region ACTIVE
#/Generator/ScintGenerator/nphotons 100000
/Generator/ScintGenerator/nphotons 100

# PHYSICS
/control/execute macros/physics/IonizationElectron.mac
/nexus/persistency/output_file S1_param.next
