## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO_S2_table.init.mac
##
## Initialization macro to simulate secondary scintillation light
## for look-up tables in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics

/nexus/RegisterGeometry NextHDDEMOOpticalGeometry

/nexus/RegisterGenerator ScintillationGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterTrackingAction DefaultTrackingAction

/nexus/RegisterMacro macros/NEXTHDDEMO_S2_table.config.mac
