## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO_full.config.mac
##
## Configuration macro to simulate Kr-83 decays in the NEXT-20. geometry
## with generation and transportation of optical photons.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/nexus/random_seed -1

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/NextHDDEMO/pressure 20. bar
/Geometry/NextHDDEMO/max_step_size 1. mm
/Geometry/NextHDDEMO/field_cage_vis 0

## EL______________________________________________________
/Geometry/NextHDDEMO/elfield false
/Geometry/NextHDDEMO/EL_field 13 kV/cm

## difusion______________________________________________________
/Geometry/NextHDDEMO/drift_transv_diff 0. mm/sqrt(cm)
/Geometry/NextHDDEMO/drift_long_diff 0. mm/sqrt(cm)
/Geometry/NextHDDEMO/ELtransv_diff 0. mm/sqrt(cm)
/Geometry/NextHDDEMO/ELlong_diff 0. mm/sqrt(cm)


## fibers______________________________________________________
/Geometry/NextHDDEMO/fiber_type Y11 ### (Y11, B2)
/Geometry/NextHDDEMO/coated true

## sensor______________________________________________________
/Geometry/NextHDDEMO/sensor_type SiPM_Hamamatsu ### (PERFECT, SiPM_FBK, SiPM_Hamamatsu, PMT)
/Geometry/NextHDDEMO/sensor_visibility true

## teflon______________________________________________________
/Geometry/NextHDDEMO/cap_visibility false
/Geometry/NextHDDEMO/panels_visibility false


/process/optical/processActivation Cerenkov false

##### GENERATOR #####
#/Geometry/NextHDDEMO/vertex_zpos ACTIVE_CENTER ### (ACTIVE_CENTER, ACTIVE_END)
/Generator/SingleParticle/region ACTIVE

# Single Particle____________________________________________
/Generator/SingleParticle/particle ie-
/Generator/SingleParticle/min_energy 1 eV
/Generator/SingleParticle/max_energy 1 eV
/Generator/SingleParticle/momentum 0 0 0


##### PHYSICS #####

/PhysicsList/Nexus/clustering          false # base-state false
/PhysicsList/Nexus/drift               true  # base-state true
/PhysicsList/Nexus/electroluminescence false  # base-state true
/PhysicsList/Nexus/photoelectric       false # base-state false



##### PERSISTENCY #####
/nexus/persistency/output_file NextHDDEMO_ie_s2.next
