## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO_debug.init.mac
##
## Initialization macro to simulate geantinos crossing the NEXT-10. detector.
## It is useful to debug the geometry.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/nexus/RegisterGeometry NextHDDEMOOpticalGeometry
#/nexus/RegisterGeometry NextHDDEMO

#/nexus/RegisterGenerator SingleParticleGenerator
/nexus/RegisterGenerator ScintillationGenerator

/nexus/RegisterMacro macros/NEXTHDDEMO_debug.config.mac
