## ----------------------------------------------------------------------------
## nexus | NEXT100fibers_debug.init.mac
##
## Initialization macro to simulate geantinos crossing the NEXT-100 detector.
## It is useful to debug the geometry.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/nexus/RegisterGeometry Next100fibers

/nexus/RegisterGenerator SingleParticleGenerator

/nexus/RegisterMacro macros/NEXT100fibers_debug.config.mac
