## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO_full.init.mac
##
## Initialization macro to simulate Kr-83 decays in the NEXT-20. geometry
## with generation and transportation of optical photons.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/nexus/RegisterGeometry NextHDDEMOOpticalGeometry

/nexus/RegisterGenerator Kr83mGenerator


/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
#/nexus/RegisterEventAction DefaultEventAction

#/nexus/RegisterTrackingAction DefaultTrackingAction
#/nexus/RegisterTrackingAction OpticalTrackingAction
/nexus/RegisterTrackingAction noOpticalTrackingAction

/nexus/RegisterSteppingAction AnalysisSteppingAction

/nexus/RegisterMacro macros/NEXTHDDEMO_Kr.config.mac
