## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO.Neutron.config.mac
##
## Configuration macro to simulate neutrons from all around the lead shielding
## in the NEXT-20. detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0
/process/had/verbose 0

##### JOB CONTROL #####
/nexus/random_seed -1

##### GEOMETRY #####
/Geometry/NextHDDEMO/pressure 20. bar
/Geometry/NextHDDEMO/max_step_size 1. mm
/Geometry/NextHDDEMO/elfield false

/control/execute macros/geometries/NEXTHDDEMODefaultVisibility.mac

##### GENERATOR #####
# Neutron generator for cosmogenics
/Generator/SingleParticle/particle neutron
/Generator/SingleParticle/min_energy 20. MeV
/Generator/SingleParticle/max_energy 20. MeV
/Generator/SingleParticle/region EXTERNAL

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

##### PERSISTENCY #####
/nexus/persistency/event_type background
/nexus/persistency/output_file NextHDDEMO.Neutron.next
