## ----------------------------------------------------------------------------
## nexus | NEXT100fibers_full.config.mac
##
## Configuration macro to simulate Kr-83 decays in the NEXT-100 geometry
## with generation and transportation of optical photons.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100fibers/elfield true
/Geometry/Next100fibers/EL_field 13 kV/cm
/Geometry/Next100fibers/pressure 10. bar
/Geometry/Next100fibers/max_step_size 1. mm

/process/optical/processActivation Cerenkov false

##### GENERATOR #####
/Generator/Kr83mGenerator/region ACTIVE

##### PERSISTENCY #####
/nexus/persistency/output_file Next100fibers_full.next
