## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO_muons.config.mac
##
## Configuration macro to simulate muons according in the NEXT-10. geometry.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

### VERBOSITY
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0
/process/had/verbose 0

### JOB CONTROL
/nexus/random_seed 17392

### GEOMETRY
/Geometry/NextHDDEMO/pressure 10.bar
/Geometry/NextHDDEMO/gas enrichedXe
/Geometry/NextHDDEMO/elfield false
#/Geometry/NextHDDEMO/lab_walls true # Turn on when using HALLA_OUTER region

### GENERATOR

# Choose where to generate muons. 
# EXTERNAL:    Just outside lead castle
# HALLA_OUTER: Hall A walls
/Generator/MuonGenerator/region EXTERNAL 
# /Generator/MuonGenerator/region HALLA_OUTER

# Use angular distribution simulated/measured at LSC
/Generator/MuonGenerator/use_lsc_dist true

# User specified muon direction. Must set use_lsc_dist to false for this to work
# /Generator/MuonGenerator/user_dir 0 -1 0

# Angle only: za, # Angle + Energy: zae
/Generator/MuonGenerator/angle_dist zae

# DataFile: data/MuonAnaAllRuns.csv, # SimulationFile: data/SimulatedMuonsProposalMCEq.csv
# SimulationFile (Angle + Energy): data/SimulatedMuonsProposalMCEqEnergy.csv
/Generator/MuonGenerator/angle_file data/SimulatedMuonsProposalMCEqEnergy.csv

/Generator/MuonGenerator/min_energy 10. GeV
/Generator/MuonGenerator/max_energy 5500 GeV

# For coordinate system transformation, do not edit
/Generator/MuonGenerator/azimuth_rotation 10. deg

### ACTIONS
/Actions/DefaultEventAction/min_energy 0.01 MeV
#/Actions/MuonsEventAction/stringHist MuonsDistribution.csv


### PHYSICS (for fast simulation)
/PhysicsList/Nexus/clustering           false
/PhysicsList/Nexus/drift                false
/PhysicsList/Nexus/electroluminescence  false

### PERSISTENCY
/nexus/persistency/start_id 0
/nexus/persistency/save_strings false
/nexus/persistency/output_file NextHDDEMOMuons_example.next
