## ----------------------------------------------------------------------------
## nexus | NEXT100.config.mac
##
## Configuration macro to simulate Bi-214 radioactive decays from thethe
## copper plate of the tracking plane in the NEXT-100 detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/elfield true
/Geometry/Next100/max_step_size 1. mm
/Geometry/Next100/field_cage_vis 0

## fibers______________________________________________________
/Geometry/Next100/fiber_type Y11 ### (Y11, B2)
/Geometry/Next100/coated true

## sensor______________________________________________________
/Geometry/Next100/sensor_type SiPM_Hamamatsu ### (PERFECT, SiPM_FBK, SiPM_Hamamatsu, PMT)
/Geometry/Next100/sensor_visibility true

## teflon______________________________________________________
/Geometry/Next100/cap_visibility false
/Geometry/Next100/panels_visibility true

##### GENERATOR #####
/Generator/IonGenerator/atomic_number 83
/Generator/IonGenerator/mass_number 214
/Generator/IonGenerator/region ACTIVE

##### ACTIONS #####
/Actions/DefaultEventAction/min_energy 0.6 MeV
/Actions/DefaultEventAction/max_energy 2.55 MeV

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

##### PERSISTENCY #####
/nexus/persistency/output_file Next100.next
## eventType options: bb0nu, bb2nu, background
/nexus/persistency/event_type bb2nu
