## ----------------------------------------------------------------------------
## nexus | NEXT100fibersopt_ovlp.config.mac
##
## Initialization macro to simulate Kr-83 decays in the NEXT-100 geometry
## with fast simulation and grids implemented as dielectric,
## with the purpose of checking for overlaps in a reasonable amount of time.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100fibers/elfield false
/Geometry/Next100fibers/pressure 10. bar
/Geometry/Next100fibers/max_step_size 1. mm
/Geometry/Next100fibers/use_dielectric_grid true

##### GENERATOR #####
/Generator/Kr83mGenerator/region ACTIVE

##### PHYSICS #####
## No full simulation
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

##### PERSISTENCY #####
/nexus/persistency/output_file Next100fibersopt_ovlp.next
